sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - chmod +x mvnw
  - sudo apt-get install jq
  - curl -LSs $(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url') -o codacy-coverage-reporter-assembly.jar

after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: clinical-centre-system